spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/skidkilife
    username: postgres
    password: Windows12!@
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 15MB
      max-request-size: 15MB

application:
  bucket-name: skidkilife.appspot.com
  download-url: https://console.firebase.google.com/project/skidkilife/storage/skidkilife.appspot.com/files