CREATE TABLE if not exists establishments (
    id bigint NOT NULL,
    description text,
    from_work_schedule time without time zone,
    establishment_name text,
    created_date date,
    is_activated boolean,
    is_enabled boolean,
    longitude decimal,
    latitude decimal,
    address character varying(255),
    phone_number text,
    password text,
    image text,
    to_work_schedule time without time zone,
    establishment_type character varying(255),
    role_id bigint
    );

ALTER TABLE establishments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME establishments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE if not exists work_schedules (
  id bigint NOT NULL,
  day character varying(255)
    );

ALTER TABLE work_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME work_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE if not exists roles (
  id bigint NOT NULL,
  role_name character varying(255)
    );

ALTER TABLE roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE if not exists user_roles (
 user_id bigint NOT NULL,
 role_id bigint NOT NULL
);

CREATE TABLE if not exists sales (
 id bigint NOT NULL,
 cost double precision,
 description text,
 discount integer,
 title text,
 establishment_id bigint,
 fromDate date,
 toDate date,
 image text,
 createdDate date
);

ALTER TABLE sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE if not exists establishment_work_schedules (
    establishment_id bigint NOT NULL,
    day_id bigint NOT NULL
);

CREATE TABLE if not exists skidki_employees (
    id bigint NOT NULL,
    name character varying(255),
    employee_created_at date,
    major character varying(255),
    phone_number character varying(255),
    password character varying(255),
    role_id bigint
    );

ALTER TABLE skidki_employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME skidki_employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

create table if not exists sms_verification (
    id bigint NOT NULL,
    code character varying(255),
    phone_number character varying(255)
    );

ALTER TABLE sms_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME sms_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);